server:
  port: 8888
  servlet:
    context-path: /

spring:
  datasource:
   type: com.alibaba.druid.pool.DruidDataSource
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/wash_Shoes?serverTimezone=Asia/Shanghai
   username: root
   password: root

mybatis-plus:
  global-config:
    db-config:
      id-type: auto #id生成规则：数据库id自增
  configuration:
    map-underscore-to-camel-case: false  # 开启驼峰功能
    auto-mapping-behavior: full # 自动映射任何复杂的结果
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启控制台 SQL 日志打印
  mapper-locations: classpath:mybatis/mapper/*.xml